# Generated by Django 4.1.4 on 2022-12-22 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_rename_address_1_client_address1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='thing',
        ),
    ]
