# Generated by Django 4.1.4 on 2022-12-22 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0003_remove_client_thing'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='thing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='things.thing'),
        ),
    ]
